
package resto_80.Vistas;


public class gestion extends javax.swing.JInternalFrame {

    
    public gestion() {
        initComponents();
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMEmpleados = new javax.swing.JMenu();
        jMIEmpleados = new javax.swing.JMenuItem();
        jMMesas = new javax.swing.JMenu();
        jMIMesas = new javax.swing.JMenuItem();
        jMProductos = new javax.swing.JMenu();
        jMIProductos = new javax.swing.JMenuItem();
        jMIPrecios = new javax.swing.JMenuItem();
        jMIStock = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jMEmpleados.setText("Empleados");

        jMIEmpleados.setText("Gestion de empleados");
        jMIEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEmpleadosActionPerformed(evt);
            }
        });
        jMEmpleados.add(jMIEmpleados);

        jMenuBar1.add(jMEmpleados);

        jMMesas.setText("Mesas");

        jMIMesas.setText("Gestion de mesas");
        jMIMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMesasActionPerformed(evt);
            }
        });
        jMMesas.add(jMIMesas);

        jMenuBar1.add(jMMesas);

        jMProductos.setText("Productos");

        jMIProductos.setText("Gestion de productos");
        jMIProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProductosActionPerformed(evt);
            }
        });
        jMProductos.add(jMIProductos);

        jMIPrecios.setText("Lista de Precios");
        jMIPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPreciosActionPerformed(evt);
            }
        });
        jMProductos.add(jMIPrecios);

        jMIStock.setText("Stock");
        jMIStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIStockActionPerformed(evt);
            }
        });
        jMProductos.add(jMIStock);

        jMenuBar1.add(jMProductos);

        jMenu1.setText("Consultas");

        jMenuItem1.setText("Cierre de caja");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Pedidos por mesero");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Pedido por mesa");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEmpleadosActionPerformed
       
        escritorio.removeAll();
        escritorio.repaint();
        gestionEmpleados gde = new gestionEmpleados ();
        gde.setVisible(true);
        escritorio.add(gde);
        escritorio.moveToFront(gde);
        
               
        
    }//GEN-LAST:event_jMIEmpleadosActionPerformed

    private void jMIStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIStockActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        gestionStock gds = new gestionStock ();
        gds.setVisible(true);
        escritorio.add(gds);
        escritorio.moveToFront(gds);
    }//GEN-LAST:event_jMIStockActionPerformed

    private void jMIMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMesasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        gestionMesas gdm = new gestionMesas ();
        gdm.setVisible(true);
        escritorio.add(gdm);
        escritorio.moveToFront(gdm);
    }//GEN-LAST:event_jMIMesasActionPerformed

    private void jMIProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProductosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        gestionProductos gdp = new gestionProductos ();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);
    }//GEN-LAST:event_jMIProductosActionPerformed

    private void jMIPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPreciosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        gestionListaPrecios glp = new gestionListaPrecios ();
        glp.setVisible(true);
        escritorio.add(glp);
        escritorio.moveToFront(glp);
    }//GEN-LAST:event_jMIPreciosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMEmpleados;
    private javax.swing.JMenuItem jMIEmpleados;
    private javax.swing.JMenuItem jMIMesas;
    private javax.swing.JMenuItem jMIPrecios;
    private javax.swing.JMenuItem jMIProductos;
    private javax.swing.JMenuItem jMIStock;
    private javax.swing.JMenu jMMesas;
    private javax.swing.JMenu jMProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
