package resto_80.Vistas;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import resto_80.Datos.EmpleadoD;
import resto_80.Datos.MesaD;
import resto_80.Datos.PedidoD;
import resto_80.Datos.ProductoD;
import resto_80.Datos.ProductoPedidoD;
import resto_80.Entidades.Empleado;
import resto_80.Entidades.Mesa;
import resto_80.Entidades.Pedido;
import resto_80.Entidades.Producto;
import resto_80.Entidades.ProductoPedido;

public class Salon extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {

        public boolean isCellEditable(int f, int c) {

            if (c == 1) {

                return true;
            } else {
                return false;
            }
        }

    };

    int npedido;

    public Salon() {

        initComponents();
        panel2.setVisible(false);
        cargarMesas();
        armarCabecera();
        cargarMeseros();
        cargarProductos();
        this.getContentPane().setBackground(Color.orange);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        camarero = new javax.swing.JComboBox<>();
        productos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        cargarProd = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jBguardar = new javax.swing.JButton();
        nmesa = new javax.swing.JLabel();
        jBNuePedido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jBcobrar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);

        panel1.setBackground(new java.awt.Color(51, 255, 204));
        panel1.setDoubleBuffered(false);
        panel1.setLayout(new java.awt.GridLayout(3, 0));

        camarero.setEnabled(false);

        productos.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Camarero");
        jLabel1.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Productos");
        jLabel3.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad");
        jLabel4.setEnabled(false);

        cantidad.setEnabled(false);

        cargarProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cargarProd.setText("Cargar Producto");
        cargarProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cargarProd.setEnabled(false);
        cargarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarProdActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eliminar.setText("Eliminar Producto");
        eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminar.setEnabled(false);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel45.setText("MESA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total:");
        jLabel5.setEnabled(false);

        total.setEditable(false);
        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total.setText("$");
        total.setEnabled(false);

        jBguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBguardar.setText("GUARDAR");
        jBguardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBguardar.setEnabled(false);
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        nmesa.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        nmesa.setText("N°");

        jBNuePedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBNuePedido.setText("NUEVO PEDIDO");
        jBNuePedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBNuePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuePedidoActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                        .addComponent(cargarProd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(eliminar))
                                    .addComponent(cantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(camarero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(panel2Layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(jLabel45)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel2Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jBNuePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel2Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jBguardar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBNuePedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(camarero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarProd)
                    .addComponent(eliminar))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(jBguardar)
                .addGap(299, 299, 299))
        );

        jBcobrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBcobrar.setText("COBRAR");
        jBcobrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBcobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBcobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBcobrar)
                        .addGap(6, 6, 6)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarProdActionPerformed
        try {
            ProductoD pD = new ProductoD();
            
            Producto p = (pD.buscarProductoxNombre(productos.getSelectedItem() + ""));

            int filasinicial=tabla.getRowCount()-1;
            
            if(filasinicial==-1){
                    String n = p.getNombre();
                    int c = Integer.parseInt(cantidad.getText());
                    double precio = c * p.getPrecio();

                    modelo.addRow(new Object[]{n, c, c * p.getPrecio()});
                    
            
                int filas = tabla.getRowCount() - 1;
                double subtotal = 0;
                for (int i = 0; i <= filas; i++) {

                subtotal = subtotal + (Double.parseDouble(tabla.getValueAt(i, 2).toString()));

                }
                total.setText(subtotal + "");
                cantidad.setText("");
            }else{
                
                int filas=tabla.getRowCount()-1;
                int rep=0;
                        
                for (int i = 0; i <= filas; i++) {

                    if (productos.getSelectedItem().toString().equalsIgnoreCase(tabla.getValueAt(i, 0)+"")) {

                        rep++;
                    }
                }
                
                if(rep==0){
                    String n = p.getNombre();
                    int c = Integer.parseInt(cantidad.getText());
                    double precio = c * p.getPrecio();

                    modelo.addRow(new Object[]{n, c, c * p.getPrecio()});
                    
            
                int filas1 = tabla.getRowCount() - 1;
                double subtotal = 0;
                for (int i = 0; i <= filas1; i++) {

                subtotal = subtotal + (Double.parseDouble(tabla.getValueAt(i, 2).toString()));

                }
                total.setText(subtotal + "");
                cantidad.setText("");
                    
                    
                    
                }else{
                    
                    JOptionPane.showMessageDialog(null, "Producto ya cargado, modifique las cantidades desde la tabla");
                    cantidad.setText("");
                    
                }

            }
  
          
        }catch(NumberFormatException ex){
           
           if(cantidad.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(null, "Debe ingresar la cantidad de productos solicitados");
           }else{
               JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
           }
           
          
        }
        
    }//GEN-LAST:event_cargarProdActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try {
            modelo.removeRow(tabla.getSelectedRow());
            int filas = tabla.getRowCount() - 1;
            double subtotal = 0;
            for (int i = 0; i <= filas; i++) {

                subtotal = subtotal + (Double.parseDouble(tabla.getValueAt(i, 2).toString()));

            }
            total.setText(subtotal + "");
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "No hay productos para eliminar");
        }


    }//GEN-LAST:event_eliminarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        try{
        Empleado emp=new Empleado();
        EmpleadoD empD=new EmpleadoD();
        PedidoD pedD = new PedidoD();
        Pedido ped = pedD.buscarPedido(npedido);
        ProductoD pD = new ProductoD();
        ProductoPedido pp = new ProductoPedido();
        ProductoPedidoD ppD = new ProductoPedidoD();
        int filas = tabla.getRowCount() - 1;
        for (int i = 0; i <= filas; i++) {

            Producto p = pD.buscarProductoxNombre(tabla.getValueAt(i, 0) + "");

            pp.setProducto(p);
            pp.setCantidad(Integer.parseInt(tabla.getValueAt(i, 1) + ""));
//            pp.setSubtotal(Double.parseDouble(tabla.getValueAt(i, 2) + ""));
            pp.setPedido(ped);

            ppD.cargarPP(pp);
        }

        ped.setMesero(empD.buscarEmpleadoNombre(camarero.getSelectedItem()+""));
        ped.setImporte(Double.parseDouble(total.getText()+""));
        
        pedD.modificarPedido(ped);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Debe agregar un producto");
            
        } 
         
        
        camarero.setEnabled(false);
        cantidad.setText("");
        cantidad.setEnabled(false);
        productos.setEnabled(false);
        borrarTabla();
        tabla.setEnabled(false);
        total.setEnabled(false);
        total.setText("");
        jLabel1.setEnabled(false);
        jLabel3.setEnabled(false);
        jLabel4.setEnabled(false);
        jLabel5.setEnabled(false);
        cargarProd.setEnabled(false);
        eliminar.setEnabled(false);
        jBguardar.setEnabled(false);
        
            
        
        panel2.setVisible(false);


    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBNuePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuePedidoActionPerformed

        camarero.setEnabled(true);
        cantidad.setEnabled(true);
        productos.setEnabled(true);
        total.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel5.setEnabled(true);
        cargarProd.setEnabled(true);
        eliminar.setEnabled(true);
        jBguardar.setEnabled(true);

        PedidoD peD = new PedidoD();
        EmpleadoD empD = new EmpleadoD();
        MesaD mesaD = new MesaD();

        Pedido ped = new Pedido();

        ped.setMesa(mesaD.buscarMesaXNumero(Integer.parseInt(nmesa.getText())));
        ped.setMesero(empD.buscarEmpleadoNombre(camarero.getSelectedItem() + ""));
        ped.setF_H(LocalDateTime.now());
        ped.setEstado(false);
        ped.setImporte(0);
        peD.agregarPedido(ped);

        npedido = ped.getIdPedido();


    }//GEN-LAST:event_jBNuePedidoActionPerformed

    private void jBcobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcobrarActionPerformed

        panel2.setVisible(false);
        panel2.setEnabled(false);
        panel1.setVisible(false);
        panel1.setEnabled(false);
       jBcobrar.setVisible(false);
       jBcobrar.setEnabled(false);
       Facturacion fac= new Facturacion();
       fac.setVisible(true);
       this.add(fac);
       this.moveToFront();
       
       
    }//GEN-LAST:event_jBcobrarActionPerformed

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
      try{
    ProductoD pD = new ProductoD();
    int filaselec=tabla.getSelectedRow();
    
            Producto p = (pD.buscarProductoxNombre(tabla.getValueAt(filaselec,0)+""));
        
                String n = p.getNombre();
                    int c = Integer.parseInt(tabla.getValueAt(filaselec, 1)+"");
                    double precio = c * p.getPrecio();

                    
                 tabla.setValueAt(precio, tabla.getSelectedRow(), 2);
            
                int filas1 = tabla.getRowCount() - 1;
                double subtotal = 0;
                for (int i = 0; i <= filas1; i++) {

                subtotal = subtotal + (Double.parseDouble(tabla.getValueAt(i, 2).toString()));

                }
                total.setText(subtotal + "");
                cantidad.setText("");
        
        
    }catch(NumberFormatException ex){
           int filaselec=tabla.getSelectedRow();
           if((tabla.getValueAt(filaselec, 1)+"").equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(null, "Debe ingresar la cantidad de productos solicitados");
           }else{
               JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
               tabla.setValueAt("", tabla.getSelectedRow(), 1);
           }
    }
    }//GEN-LAST:event_tablaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> camarero;
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton cargarProd;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jBNuePedido;
    public javax.swing.JButton jBcobrar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nmesa;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JComboBox<String> productos;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.addColumn("Productos");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Sub Total");

        tabla.setModel(modelo);
    }

    private void cargarMeseros() {
        EmpleadoD ed = new EmpleadoD();

        for (Empleado e : ed.listarEmpleados()) {

            if (e.isEstado() == true) {
                camarero.addItem(e.getNombre_apellido());
            }
        }
    }

    private void cargarProductos() {
        ProductoD pd = new ProductoD();

        for (Producto p : pd.listarProductos()) {

            if (p.isEstado() == true) {
                productos.addItem(p.getNombre());
            }
        }
    }

    //carga las mesas que ya estan credas en la base de datos en el panel:
    private void cargarMesas() {

        MesaD md = new MesaD();

        ArrayList<Mesa> mesas = (ArrayList<Mesa>) md.listarMesas();

        for (Mesa m : mesas) {

            JButton boton = new JButton();

            boton.setName(m.getNumeroMesa() + "");

            boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mesa.jpeg")));
            boton.setText(boton.getName());

            boton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    panel2.setVisible(true);
                    nmesa.setText(boton.getName());
                }
            });

            panel1.add(boton);
            panel1.updateUI();

        }
    }


private void borrarTabla(){
    
    int filas = tabla.getRowCount()-1;
    
    for(; filas>=0;filas--){
        
        modelo.removeRow(filas);
    }
    
    
    
}


}